name: .NET Pull requests

on:
  pull_request:
    branches: [ master, stable ]
    paths-ignore:
    - '**.md'
    - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: eform-angular-inventory-plugin
      - name: 'Preparing Frontend checkout'
        uses: actions/checkout@v3
        with:
          repository: microting/eform-angular-frontend
          ref: stable
          path: eform-angular-frontend
      - name: Copy dependencies
        run: |
          cp -av eform-angular-inventory-plugin/eform-client/src/app/plugins/modules/inventory-pn eform-angular-frontend/eform-client/src/app/plugins/modules/inventory-pn
          cd eform-angular-frontend/eform-client && ../../eform-angular-inventory-plugin/testinginstallpn.sh
      - name: Copy Dockerfile
        run: cp eform-angular-inventory-plugin/Dockerfile .
      - name: Build Docker image
        id: build
        run: |
          pwd
          ls -lah
          docker build . -t microtingas/frontend-container:latest --build-arg GITVERSION=1.0.0 --build-arg PLUGINVERSION=1.0.0
        shell: bash
      - run: docker save microtingas/frontend-container:latest -o inventory-container.tar
      - uses: actions/upload-artifact@v4
        with:
          name: inventory-container
          path: inventory-container.tar
  test:
    needs: build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
    - uses: actions/download-artifact@v4
      with:
        name: inventory-container
    - run: docker load -i inventory-container.tar
    - name: Create docker network
      run: docker network create --driver bridge --attachable data
    - name: Start MariaDB
      run: |
        docker pull mariadb:10.8
        docker run --name mariadbtest --network data -e MYSQL_ROOT_PASSWORD=secretpassword -p 3306:3306 -d mariadb:10.8
    - name: Start rabbitmq
      run: |
        docker pull rabbitmq:latest
        docker run -d --hostname my-rabbit --name some-rabbit --network data -e RABBITMQ_DEFAULT_USER=admin -e RABBITMQ_DEFAULT_PASS=password rabbitmq:latest
    - name: Sleep 15
      run: sleep 15
    - name: Start the newly build Docker container
      id: docker-run
      run: docker run --name my-container -p 4200:5000 --network data microtingas/frontend-container:latest "/ConnectionString=host=mariadbtest;Database=420_Angular;user=root;password=secretpassword;port=3306;Convert Zero Datetime = true;SslMode=none;" > docker_run_log 2>&1 &
    - name: Use Node.ts
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: 'Preparing Frontend checkout'
      uses: actions/checkout@v3
      with:
        repository: microting/eform-angular-frontend
        ref: stable
        path: eform-angular-frontend
    - name: Copy dependencies
      run: |
        cp -av main/eform-client/src/app/plugins/modules/inventory-pn eform-angular-frontend/eform-client/src/app/plugins/modules/inventory-pn
        cp -av main/eform-client/e2e/Tests/inventory-settings eform-angular-frontend/eform-client/e2e/Tests/inventory-settings
        cp -av main/eform-client/e2e/Tests/inventory-general eform-angular-frontend/eform-client/e2e/Tests/inventory-general
        cp -av main/eform-client/e2e/Page\ objects/Inventory eform-angular-frontend/eform-client/e2e/Page\ objects/Inventory
        cp -av main/eform-client/wdio-headless-plugin-step2.conf.js eform-angular-frontend/eform-client/wdio-headless-plugin-step2.conf.js
        cp -av main/eform-client/wdio-plugin-step2.conf.js eform-angular-frontend/eform-client/wdio-plugin-step2.conf.js
        mkdir -p eform-angular-frontend/eFormAPI/eFormAPI.Web/Plugins
        cp -av main/eFormAPI/eFormAPI.Web/Plugins/Inventory eform-angular-frontend/eFormAPI/eFormAPI.Web/Plugins/Inventory
        cd eform-angular-frontend/eform-client && ../../main/testinginstallpn.sh
    - name: yarn install
      run: cd eform-angular-frontend/eform-client && yarn install
    - name: Create errorShots directory
      run: mkdir /home/runner/work/eform-angular-inventory-plugin/eform-angular-inventory-plugin/eform-angular-frontend/eform-client/errorShots
    - name: Pretest changes to work with Docker container
      run: sed -i 's/localhost/mariadbtest/g' eform-angular-frontend/eform-client/e2e/Constants/DatabaseConfigurationConstants.ts
    - name: DB Configuration
      uses: cypress-io/github-action@v4
      with:
        start: echo 'hi'
        wait-on: "http://localhost:4200"
        wait-on-timeout: 120
        browser: chrome
        record: false
        spec: cypress/e2e/db/*
        config-file: cypress.config.ts
        working-directory: eform-angular-frontend/eform-client
        command-prefix: "--"
    - name: Plugin testing
      run: cd eform-angular-frontend/eform-client && npm run testheadlessplugin
    - name: The job has failed
      if: ${{ failure() }}
      run: |
        cat docker_run_log
    - name: Archive screenshot artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: error Screenshots
        path: |
          /home/runner/work/eform-angular-inventory-plugin/eform-angular-inventory-plugin/eform-angular-frontend/eform-client/errorShots/chrome*.png
          /home/runner/work/eform-angular-inventory-plugin/eform-angular-inventory-plugin/eform-angular-frontend/eform-client/cypress/videos/*.mp4
        retention-days: 2
  test-dotnet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create docker network
      run: docker network create --driver bridge --attachable data
    - name: Start MariaDB
      run: |
        docker pull mariadb:latest
        docker run --name mariadbtest --network data -e MYSQL_ROOT_PASSWORD=secretpassword -p 3306:3306 -d mariadb:latest
    - name: Start rabbitmq
      run: |
        docker pull rabbitmq:latest
        docker run -d --hostname my-rabbit --name some-rabbit --network data -e RABBITMQ_DEFAULT_USER=admin -e RABBITMQ_DEFAULT_PASS=password rabbitmq:latest
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x
    - name: Build
      run: dotnet build eFormAPI/Plugins/Inventory.Pn/Inventory.Pn.sln
    - name: Unit Tests
      run: dotnet test --no-restore -c Release -v n eFormAPI/Plugins/Inventory.Pn/Inventory.Pn.Test/Inventory.Pn.Test.csproj